on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-for-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mozilla-actions/sccache-action@v0.0.7
      - uses: actions/checkout@v4
        with:
          repository: cordx56/secret-dotfiles
          path: secret-dotfiles
          token: ${{ secrets.PAT }}
      - run: |
          cat secret-dotfiles/env/sccache >> $GITHUB_ENV
          echo RUSTC_WRAPPER=sccache >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: |
          rustup toolchain install --profile=minimal stable 
          rustup target add aarch64-apple-darwin
      - run: pnpm install
      - run: pnpm tauri build --bundles dmg
      - uses: actions/upload-artifact@v4
        with:
          name: deskvrm-release-dmg
          path: src-tauri/target/**/*.dmg
  build-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mozilla-actions/sccache-action@v0.0.7
      - uses: actions/checkout@v4
        with:
          repository: cordx56/secret-dotfiles
          path: secret-dotfiles
          token: ${{ secrets.PAT }}
      - run: |
          cat secret-dotfiles/env/sccache >> $GITHUB_ENV
          echo RUSTC_WRAPPER=sccache >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - shell: pwsh
        run: |
          rustup toolchain install --profile=minimal stable 
          rustup target add x86_64-pc-windows-msvc
      - shell: pwsh
        run: pnpm install
      - shell: pwsh
        run: pnpm tauri build --bundles msi
      - uses: actions/upload-artifact@v4
        with:
          name: deskvrm-release-msi
          path: src-tauri/target/**/*.msi
  release:
    runs-on: ubuntu-latest
    needs:
      - build-for-macos
      - build-for-windows
    steps:
      - uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: auto deskvrm release
          draft: true
          files: |
            ./**/*.dmg
            ./**/*.msi
